import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { AppProvider } from "@/context/AppContext";
import { SessionProvider } from "next-auth/react";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="mx-auto max-w-7xl">
          <SessionProvider>
            <AppProvider>
              <NavBar />
              {children}
              <Footer />
            </AppProvider>
          </SessionProvider>
        </main>
      </body>
    </html>
  );
}
